apiVersion: apps/v1
kind: Deployment
metadata:
  name: sensors-publisher
  labels:
    app: sensors-publisher
spec:
  replicas: 1
  template:
    metadata:
      name: sensors-publisher
      labels:
        app: sensors-publisher
    spec:
      containers:
        - name: sensors-publisher
          image: harbor.tap.amer.end2end.link/tap/spring-sensors-sensor
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - mountPath: /bindings/rmq
              name: service-binding
          env:
            - name: SERVICE_BINDING_ROOT
              value: /bindings
      restartPolicy: Always
      volumes:
        - name: service-binding
          projected:
            sources:
              - secret:
                  name: rmq-1-default-user
  selector:
    matchLabels:
      app: sensors-publisher
