apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: spring-sensors
  labels:
    apps.tanzu.vmware.com/workload-type: web
spec:
  source:
    git:
      url: https://github.com/tanzu-end-to-end/spring-sensors.git
      ref:
        branch: main
